name: Repo structure validate
on:
  pull_request:
    branches:
      - main
    workflow_dispatch:

jobs:
  checkout:
    uses: actions/checkout@v4.1.5

  validate:
    uses: actions/setup-python@5.1.0
    run: python structure_validate.py

