name: Repo structure validate
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    name: Repo structure
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate
      run: python structure_validate.py
