name: Repo structure validate
on:
  pull_request:
    branches:
      - main
    workflow_dispatch:

jobs:
  setup_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        uses: actions/setup-python@5.1.0
        run: python structure_validate.py

